// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: mid.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息ID枚举
type MID int32

const (
	MID_None MID = 0
	// Account
	MID_UserLoginReq MID = 1000001 //用户登录
	MID_UserLoginRes MID = 1000002 //用户登录
	MID_ReconnectReq MID = 1000003 //重连
	MID_ReconnectRes MID = 1000004 //重连
)

// Enum value maps for MID.
var (
	MID_name = map[int32]string{
		0:       "None",
		1000001: "UserLoginReq",
		1000002: "UserLoginRes",
		1000003: "ReconnectReq",
		1000004: "ReconnectRes",
	}
	MID_value = map[string]int32{
		"None":         0,
		"UserLoginReq": 1000001,
		"UserLoginRes": 1000002,
		"ReconnectReq": 1000003,
		"ReconnectRes": 1000004,
	}
)

func (x MID) Enum() *MID {
	p := new(MID)
	*p = x
	return p
}

func (x MID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MID) Descriptor() protoreflect.EnumDescriptor {
	return file_mid_proto_enumTypes[0].Descriptor()
}

func (MID) Type() protoreflect.EnumType {
	return &file_mid_proto_enumTypes[0]
}

func (x MID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MID.Descriptor instead.
func (MID) EnumDescriptor() ([]byte, []int) {
	return file_mid_proto_rawDescGZIP(), []int{0}
}

var File_mid_proto protoreflect.FileDescriptor

var file_mid_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x5f, 0x0a, 0x03, 0x4d, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x10, 0xc1, 0x84, 0x3d, 0x12, 0x12, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x10, 0xc2, 0x84, 0x3d, 0x12, 0x12, 0x0a, 0x0c, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x10, 0xc3, 0x84, 0x3d, 0x12,
	0x12, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x10,
	0xc4, 0x84, 0x3d, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mid_proto_rawDescOnce sync.Once
	file_mid_proto_rawDescData = file_mid_proto_rawDesc
)

func file_mid_proto_rawDescGZIP() []byte {
	file_mid_proto_rawDescOnce.Do(func() {
		file_mid_proto_rawDescData = protoimpl.X.CompressGZIP(file_mid_proto_rawDescData)
	})
	return file_mid_proto_rawDescData
}

var file_mid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mid_proto_goTypes = []interface{}{
	(MID)(0), // 0: proto.MID
}
var file_mid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mid_proto_init() }
func file_mid_proto_init() {
	if File_mid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mid_proto_goTypes,
		DependencyIndexes: file_mid_proto_depIdxs,
		EnumInfos:         file_mid_proto_enumTypes,
	}.Build()
	File_mid_proto = out.File
	file_mid_proto_rawDesc = nil
	file_mid_proto_goTypes = nil
	file_mid_proto_depIdxs = nil
}
